name: update-sitemap
on:
  schedule:
    - cron: '0 15 * * *'
jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Ping to Google
        run: |
          curl -X GET "http://www.google.com/ping?sitemap=https://ncreators.github.io/sitemap.xml"
